[fixbug]: Fix neighbor recover failure (#8231)
What is the motivation for this PR?
The PR(#6056) introduced the following error when we need to recover the neighbor device as SONiC.

E               Failed: Processes "['_neighbor_vm_recover_config--<SonicHost VM0101>']" failed with exit code "1"
E               Exception:
E               '<class 'tests.common.devices.sonic.SonicHost'>' object has no attribute 'topo_type'
E               Traceback:
E               Traceback (most recent call last):
E                 File "/var/src/sonic-mgmt/tests/common/helpers/parallel.py", line 31, in run
E                   Process.run(self)
E                 File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
E                   self._target(*self._args, **self._kwargs)
E                 File "/var/src/sonic-mgmt/tests/common/plugins/sanity_check/recover.py", line 110, in _neighbor_vm_recover_config
E                   config_reload(node["host"])
E                 File "/var/src/sonic-mgmt/tests/common/plugins/loganalyzer/utils.py", line 24, in decorated
E                   res = func(*args, **kwargs)
E                 File "/var/src/sonic-mgmt/tests/common/config_reload.py", line 90, in config_reload
E                   ignore_t2_syslog_msgs(duthost)
E                 File "/var/src/sonic-mgmt/tests/common/helpers/dut_utils.py", line 300, in ignore_t2_syslog_msgs
E                   if duthost.topo_type == "t2" and duthost.facts.get('platform_asic') == "broadcom-dnx":
E                 File "/var/src/sonic-mgmt/tests/common/devices/base.py", line 50, in __getattr__
E                   "'%s' object has no attribute '%s'" % (self.__class__, module_name)
E               AttributeError: '<class 'tests.common.devices.sonic.SonicHost'>' object has no attribute 'topo_type'
How did you do it?
Refactor the common function, config_reload, to avoid accessing the attribute,topo_type, that was only defined for DUT when SONiC neighbor was recovered.

Signed-off-by: Ze Gan <ganze718@gmail.com>