[Python3 migration]Fix test failure in test_nhop_group.py
What is the motivation for this PR?
Test failed with following error:
File "/azp/_work/15/s/tests/ipfwd/test_nhop_group.py", line 117, in init
moff1 = "{0:x}".format(i / 255)
ValueError: Unknown format code 'x' for object of type 'float'

How did you do it?
In Python2 5/2=2. In Python3, 5/2=2.5 which is not an integer.
So use "//" instead of "/"
Search the whole code base and only find this one.

How did you verify/test it?
Manually run the test case.